steps:
  # Step 1: Install frontend dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: 'npm-install'
    args: ['install']
    dir: 'frontend'

  # Step 2: Build the static frontend
  - name: 'gcr.io/cloud-builders/npm'
    id: 'build-frontend'
    args: ['run', 'build']
    dir: 'frontend'
    waitFor: ['npm-install']

  # Step 3 Deploy Frontend to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'deploy-frontend'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-c'
      - '-d'
      - './dist'
      - 'gs://cdms.jjckrbbt.dev'
    dir: 'frontend'
    waitFor: ['build-frontend']

  # Step 4: Build the backend Docker image
  # The image is tagged with the commit SHA for versioning
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend-image'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cdms-repo/cdms-backend:${SHORT_SHA}'
      - '.'
      - '-f'
      - 'Dockerfile'
    dir: 'backend'

  # Step 5: Push the backend image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-image'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cdms-repo/cdms-backend:${SHORT_SHA}']
    waitFor: ['build-backend-image']

  # Step 6: Run DB Migratios
  - name: 'gcr.io/google-appengine/exec-wrapper'
    id:   'run-db-migrations'
    entrypoint: 'sh'

    waitFor: ['push-backend-image']
    args:
      - '-c'
      - |
       # Start the proxy in the background
        apk add --no-cache go
        /build/cloud-sql-proxy cdms-463617:us-central1:cdms-demo &
        sleep 5
        go install github.com/pressly/goose/v3/cmd/goose@latest
        DB_URL=$(gcloud secrets versions access latest --secret=cdms-database-url --project=${PROJECT_ID})
        /root/go/bin/goose -dir "backend/sql/schema" postgres "$$DB_URL" up
    availableSecrets:
      secretManager:
        - versionName: projects/${PROJECT_ID}/secrets/cdms-database-url/versions/latest
          env: 'DB_SECRET_URL'

  # Step 7: Deploy the new image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-backend'
    args:
      - 'run'
      - 'deploy'
      - 'cdms-backend'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/cdms-repo/cdms-backend:${SHORT_SHA}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--cpu-boost'
      - '--port=8080'
      - '--add-cloudsql-instances=cdms-463617:us-central1:cdms'
      - '--set-secrets=DATABASE_URL=cdms-database-url:latest,SENTRY_DSN=cdms-sentry-dsn:latest'
      - '--set-env-vars=GCS_BUCKET_NAME=your-cdms-report-bucket-name'
    waitFor: ['push-backend-image']

# Store the final image URI for reference
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cdms-repo/cdms-backend:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
